version: '3.7'

services: 
  app:
    image: node:latest
    working_dir: /apps
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - './:/apps'
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  adminer:
    image: adminer
    restart: always
    ports:
    - 1990:8080

